type User @table {
  email: String!
  passwordHash: String!
  createdAt: Timestamp!
  displayName: String!
  firstName: String
  lastName: String
  profilePictureUrl: String
  studentVerified: Boolean
}

type Portfolio @table {
  user: User!
  slug: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  isPublished: Boolean!
  customDomain: String
  title: String
  tagline: String
  aboutMe: String
}

type Project @table {
  portfolio: Portfolio!
  title: String!
  description: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  startDate: Date
  endDate: Date
  projectUrl: String
  thumbnailUrl: String
  isFeatured: Boolean
}

type Template @table {
  name: String!
  description: String!
  imageUrl: String!
  defaultFont: String
  defaultColorPalette: String
}

type PortfolioDesign @table {
  portfolio: Portfolio!
  template: Template!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  customColors: String
  customFonts: String
  layoutSettings: String
}

type SubscriptionType @table {
  name: String!
  pricePerMonth: Float!
  features: String!
  description: String
}

type UserSubscription @table {
  user: User!
  subscriptionType: SubscriptionType!
  startDate: Timestamp!
  status: String!
  endDate: Timestamp
  renewalDate: Timestamp
}